### ISSUE TITLE
Cannot find distribution for yaml in requirements.txt

### ISSUE THREAD

**Issue by Swarchal** [cxhernandez/molencoder#11]
Hi,

I just ran into a problem installing on anaconda python3.6 on ubuntu, after `python setup.py install` I got the following error:

```
Installed /home/scott/anaconda3/lib/python3.6/site-packages/molencoder-0.1a0-py3.6.egg
Processing dependencies for molencoder==0.1a0
Searching for yaml
Reading https://pypi.python.org/simple/yaml/
No local packages or working download links found for yaml
error: Could not find suitable distribution for Requirement.parse('yaml')
```

Though changing `yaml` to `pyyaml` in the `requirements.txt` file seems to have fixed it.

Not sure if this is due to my python installation or a typo, but thought it might be useful to know.

**Comment by cxhernandez** [comment]
Thanks for the report! I'm pretty sure this was a typo.
