### ISSUE TITLE
Use our own dataset?

### ISSUE THREAD

**Issue by kexinhuang12345** [cxhernandez/molencoder#13]
Hi,

Thanks for providing this great code. 

I am trying to use my own dataset of SMILES strings, I couldn't find the script for preprocessing these raw strings to the input features (I notice the data you provided is already being preprocessed). If you have any, Could you point that out to me? Thanks!

**Comment by cxhernandez** [comment]
Hi @kexinhuang12345,

Sorry, I didn't get to this issue in time. Did you figure out how to modify `parser_download.py` to do what you need?
